[profile.default]
src = "src"
out = "out-zk" 
libs = ["../lib", "../../../node_modules"]
compile = true
fallback_oz = false
mode = "0"

fs_permissions = [
    { access = "read", path = "../lib" }
]

remappings = [
  "@openzeppelin=../../../node_modules/@openzeppelin",
  "@hyperlane=../../../node_modules/@hyperlane-xyz/core/contracts",
  "contracts=src/contracts",
  "interfaces=src/interfaces",
  "solidity-stringutils=../lib/openzeppelin-foundry-upgrades/lib/solidity-stringutils",
]