-- migrate:up
ALTER TYPE intent_status RENAME VALUE 'RETURN_UNSUPPORTED' TO 'UNSUPPORTED_RETURNED';
ALTER TYPE intent_status ADD VALUE 'VERIFICATION_FAILED';

-- migrate:down
ALTER TYPE intent_status RENAME VALUE 'UNSUPPORTED_RETURNED' TO 'RETURN_UNSUPPORTED';
ALTER TYPE intent_status DROP VALUE 'VERIFICATION_FAILED';


