-- migrate:up

CREATE OR REPLACE FUNCTION public.get_intent_status_order(status public.intent_status) RETURNS integer
    LANGUAGE plpgsql IMMUTABLE
    AS $$
BEGIN
    RETURN CASE status
        WHEN 'NONE' THEN 0
        WHEN 'ADDED' THEN 10
        WHEN 'ADDED_SPOKE' THEN 11
        WHEN 'ADDED_HUB' THEN 12
        WHEN 'DEPOSIT_PROCESSED' THEN 20
        WHEN 'FILLED' THEN 30
        WHEN 'ADDED_AND_FILLED' THEN 31
        WHEN 'INVOICED' THEN 40
        WHEN 'DISPATCHED' THEN 50
        WHEN 'DISPATCHED_HUB' THEN 51
        WHEN 'DISPATCHED_SPOKE' THEN 52
        WHEN 'DISPATCHED_UNSUPPORTED' THEN 53
        WHEN 'DELIVERED' THEN 60
        WHEN 'SETTLED' THEN 70
        WHEN 'SETTLED_AND_COMPLETED' THEN 71
        WHEN 'SETTLED_AND_MANUALLY_EXECUTED' THEN 72
        WHEN 'UNSUPPORTED' THEN 80
        WHEN 'UNSUPPORTED_RETURNED' THEN 81
        ELSE 0
    END;
END;
$$;

-- migrate:down

CREATE OR REPLACE FUNCTION public.get_intent_status_order(status public.intent_status) RETURNS integer
    LANGUAGE plpgsql IMMUTABLE
    AS $$
BEGIN
    RETURN CASE status
        WHEN 'NONE' THEN 0
        WHEN 'ADDED' THEN 10
        WHEN 'ADDED_SPOKE' THEN 11
        WHEN 'ADDED_HUB' THEN 12
        WHEN 'DEPOSIT_PROCESSED' THEN 20
        WHEN 'FILLED' THEN 30
        WHEN 'ADDED_AND_FILLED' THEN 31
        WHEN 'INVOICED' THEN 40
        WHEN 'DISPATCHED' THEN 50
        WHEN 'DISPATCHED_HUB' THEN 51
        WHEN 'DISPATCHED_SPOKE' THEN 52
        WHEN 'DISPATCHED_UNSUPPORTED' THEN 53
        WHEN 'SETTLED' THEN 60
        WHEN 'SETTLED_AND_COMPLETED' THEN 61
        WHEN 'SETTLED_AND_MANUALLY_EXECUTED' THEN 62
        WHEN 'UNSUPPORTED' THEN 70
        WHEN 'UNSUPPORTED_RETURNED' THEN 71
        WHEN 'DELIVERED' THEN 80
        ELSE 0
    END;
END;
$$;
