[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
call_executor = "4Q68Tz8X42zvTBPuxJD9BosXhtx94cLXWZCUFpGPNfwL"
everclear_spoke = "4Q68Tz8X42zvTBPuxJD9BosXhtx94cLXWZCUFpGPNfwL"
spoke_gateway = "4Q68Tz8X42zvTBPuxJD9BosXhtx94cLXWZCUFpGPNfwL"
spoke_message_receiver = "4Q68Tz8X42zvTBPuxJD9BosXhtx94cLXWZCUFpGPNfwL"

[programs.devnet]
call_executor = "HGaUXXufuDrkUPPMfcSkcdhhWTyB2trE2UtjQD4ebyjK"
everclear_spoke = "4Q68Tz8X42zvTBPuxJD9BosXhtx94cLXWZCUFpGPNfwL"
spoke_gateway = "Cuuu22fpegEh5x8da14zVkUp5gwENHK3uM6JwKsdXrtW"
spoke_message_receiver = "8qp4V6EWGL6KgpMcJix5ufVSRu7JezM8sKKUgRwHncbA"

[programs.localnet]
call_executor = "HGaUXXufuDrkUPPMfcSkcdhhWTyB2trE2UtjQD4ebyjK"
everclear_spoke = "4Q68Tz8X42zvTBPuxJD9BosXhtx94cLXWZCUFpGPNfwL"
spoke_gateway = "Cuuu22fpegEh5x8da14zVkUp5gwENHK3uM6JwKsdXrtW"
spoke_message_receiver = "8qp4V6EWGL6KgpMcJix5ufVSRu7JezM8sKKUgRwHncbA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"
retry_count = 25

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
tx_retries = 50
commitment_timeout = 300000
