[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first'
sort_imports = true

[profile.default]
solc_version = '0.8.25'
libs = ["../../node_modules", "lib"]
optimizer_runs = 10_000
fs_permissions = [
    { access = "read-write", path = "./"}, 
    { access = "write", path = "./safeTransactionInputs/upgradeSpokeArray-mainnet.json" },
    { access = "write", path = "./safeTransactionInputs/upgradeSpokeArray-arbitrum.json" },
    { access = "write", path = "./safeTransactionInputs/upgradeSpokeArray-optimism.json" },
    { access = "write", path = "./safeTransactionInputs/upgradeSpokeArray-base.json" },
    { access = "write", path = "./safeTransactionInputs/upgradeSpokeArray-bnb.json" }
    ]

[profile.optimized]
via_ir = true
out = 'out-via-ir'

[profile.test]
via_ir = true
out = 'out-via-ir'

[profile.docs]
src = 'src/interfaces/'

[fuzz]
runs = 1000
max_test_rejects = 100_000

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
sepolia = "${SEPOLIA_RPC}"
op-sepolia = "${OP_SEPOLIA_RPC}"
arb-sepolia = "${ARB_SEPOLIA_RPC}"
amoy = "${AMOY_RPC}"
bsc = "${BNB_TESTNET_RPC}"
scroll-sepolia = "${SCROLL_SEPOLIA_RPC}"
alfajores = "${ALFAJORES_RPC}"
everclear-sepolia = "${EVERCLEAR_SEPOLIA_RPC}"
everclear = "${EVERCLEAR_RPC}"
zircuit = "${ZIRCUIT_RPC}"
linea = "${LINEA_RPC}"
polygon = "${POLYGON_RPC}"
avalanche = "${AVALANCHE_RPC}"
taiko = "${TAIKO_RPC}"
scroll = "${SCROLL_RPC}"
apechain = "${APECHAIN_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = "mainnet" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "sepolia" }
op-sepolia = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", chain = "11155420", url = "https://api-sepolia-optimistic.etherscan.io/api" }
arb-sepolia = { key = "${ARBISCAN_API_KEY}", chain = "421614", url = "https://api-sepolia.arbiscan.io/api" }
scroll-sepolia = { key = "${SCROLLSCAN_API_KEY}", chain = "scroll-sepolia", url = "https://api-sepolia.scrollscan.com/api" }
bsc = { key = "${BNBSCAN_API_KEY}", chain = "bsc", url = "https://api-testnet.bscscan.com/api" }
everclear-sepolia = { key = "${EVERCLEAR_API_KEY}", chain = "6398", url = "https://connext-sepolia.blockscout.com/api" }
everclear = { key = "${EVERCLEAR_API_KEY}", chain = "25327", url = "https://scan.everclear.org/api/v2" }
zircuit = { key = "${ZIRCUITSCAN_API_KEY}", chain = "48900", url = "https://explorer.zircuit.com/api/contractVerifyHardhat" }
linea = { key = "${LINEA_API_KEY}", chain = "59144", url = "https://api.lineascan.build/api" }
polygon = { key = "${POLYGONSCAN_API_KEY}", chain = "137", url = "https://api.polygonscan.com/api" }
avalanche = { key = "${AVALANCHESCAN_API_KEY}", chain = "43114", url = "https://api.routescan.io/v2/network/mainnet/evm/43114/etherscan" }
taiko = { key = "${TAIKOSCAN_API_KEY}", chain = "100", url = "https://api.taikoscan.io/api" }
scroll = { key = "${SCROLLSCAN_API_KEY}", chain = "534351", url = "https://api.scrollscan.com/api" }
apechain = { key = "${APECHAINSCAN_API_KEY}", chain = "59144", url = "https://api.apescan.io/api" }
