import {restore, reset, stub, SinonStub, SinonStubbedInstance, createStubInstance} from 'sinon';
import {Logger, expect, resolveAlerts, sendAlerts, createRequestContext} from '../../src';
import { TEST_REPORT } from './mock';
import * as telegram from '../../src/alerts/telegram';
import * as discord from '../../src/alerts/discord';
import * as betterUptime from '../../src/alerts/betteruptime';
import * as triage from '../../src/triage/interceptor';
import * as dedup from '../../src/triage/dedup';

const MOCK_TELEGRAM = { apiKey: '123', chatId: '456' };
const MOCK_BETTERUPTIME = { apiKey: '123', requesterEmail: 'email@mock' };
const MOCK_DISCORD = { url: 'https://discord.com' };
const config = {
  network: 'staging',
  telegram: MOCK_TELEGRAM,
  betterUptime: MOCK_BETTERUPTIME,
  discord: MOCK_DISCORD,
};

describe('helpers:alerts', () => {
    let telegramStub: SinonStub;
    let discordStub: SinonStub;
    let betterUptimeStub: SinonStub;
    let resolveBetterUptimeStub: SinonStub;
    let triageStub: SinonStub;
    let setAutoResolveOutcomeStub: SinonStub;
    let logger: SinonStubbedInstance<Logger>;
  
    beforeEach(() => {
      logger = createStubInstance(Logger);

      telegramStub = stub(telegram, 'alertTelegram');
      telegramStub.resolves();
      discordStub = stub(discord, 'alertDiscord');
      discordStub.resolves();
      betterUptimeStub = stub(betterUptime, 'alertViaBetterUptimeIfNeeded');
      betterUptimeStub.resolves();
      resolveBetterUptimeStub = stub(betterUptime, 'resolveAlertViaBetterUptime');
      resolveBetterUptimeStub.resolves();
      triageStub = stub(triage, 'triageInterceptor');
      triageStub.resolves({ report: TEST_REPORT, shouldAutoResolve: false });
      setAutoResolveOutcomeStub = stub(dedup, 'setAutoResolveOutcome');
      setAutoResolveOutcomeStub.resolves();
    });
  
    afterEach(() => {
      restore();
      reset();
    });
  
    describe('#sendAlerts', () => {
      it('should work', async () => {
        expect(sendAlerts(TEST_REPORT, logger, config, createRequestContext('test'))).to.be.not.throw;
      });

      it('routes to BetterUptime resolve path when triage auto-resolve is enabled', async () => {
        triageStub.resolves({
          report: TEST_REPORT,
          shouldAutoResolve: true,
          fingerprint: 'fp-1',
        });

        await sendAlerts(TEST_REPORT, logger, config, createRequestContext('test'));

        expect(resolveBetterUptimeStub.calledOnce).to.be.true;
        expect(betterUptimeStub.called).to.be.false;
        expect(setAutoResolveOutcomeStub.calledOnceWithExactly('fp-1', true, 'auto_resolve_dispatched')).to.be.true;
      });

      it('persists failed auto-resolve dispatch outcome', async () => {
        triageStub.resolves({
          report: TEST_REPORT,
          shouldAutoResolve: true,
          fingerprint: 'fp-2',
        });
        resolveBetterUptimeStub.rejects(new Error('dispatch failed'));

        await sendAlerts(TEST_REPORT, logger, config, createRequestContext('test'));

        expect(setAutoResolveOutcomeStub.calledOnceWithExactly('fp-2', false, 'auto_resolve_dispatch_failed')).to.be.true;
      });

      it('logs a sanitized report snapshot', async () => {
        triageStub.resolves({
          report: { ...TEST_REPORT, reason: 'token=supersecretvalue' },
          shouldAutoResolve: false,
        });

        await sendAlerts(TEST_REPORT, logger, config, createRequestContext('test'));

        expect(logger.warn.called).to.be.true;
        const logCtx = logger.warn.getCall(0).args[3];
        expect(logCtx).to.have.property('report');
        expect(logCtx.report.reason).to.not.include('supersecretvalue');
      });
    });

    describe('#resolveAlerts', () => {
      it('should resolve alerts generated by sendAlerts', async () => {
        await sendAlerts(TEST_REPORT, logger, config, createRequestContext('test'));
        await resolveAlerts(TEST_REPORT, logger, config, createRequestContext('test'));
        expect(betterUptimeStub.getCalls().length).to.be.eq(1);
        expect(resolveBetterUptimeStub.getCalls().length).to.be.eq(1);

        const alertReport = betterUptimeStub.getCall(0).args[0];
        const resolveReport = resolveBetterUptimeStub.getCall(0).args[0];
        
        expect(alertReport.severity).to.be.eq(resolveReport.severity);
        expect(alertReport.reason).to.be.eq(resolveReport.reason);
        expect(alertReport.env).to.be.eq(resolveReport.env);
        expect(alertReport.ids).to.be.eq(resolveReport.ids);
        expect(alertReport.timestamp).to.be.eq(resolveReport.timestamp);
        expect(alertReport.type).to.be.eq(resolveReport.type);
      })
    });
  });
