name: everclear-indexer
description: Indexes IntentAdded and IntentFilled events from EverclearSpoke contracts across all mainnet chains

# Configure which fields to include from events
field_selection:
  transaction_fields:
    - "hash"

# Define the contract ABIs
contracts:
  - name: EverclearSpoke
    abi_file_path: ./abis/EverclearSpoke.json
    handler: ./src/EventHandlers.ts
    events:
      - event: IntentAdded
      - event: IntentFilled
  
  - name: FeeAdapter
    abi_file_path: ./abis/FeeAdapter.json
    handler: ./src/EventHandlers.ts
    events:
      - event: IntentWithFeesAdded

# Define all networks
# NOTE: we are using reorg-safe values from hyperlane: https://docs.hyperlane.xyz/docs/reference/addresses/validators/latencies
networks:
  - id: 1
    start_block: 20760959
    confirmed_block_threshold: 15
    contracts:
      - name: EverclearSpoke
        address: 0xD95Ff203bAAd65A8Fafd5C3dB695FC0a77A809a3
      - name: FeeAdapter
        address: 0x7621D1085559Ab35513E2a41EC948a8524F619D9

  - id: 10
    start_block: 0
    confirmed_block_threshold: 10
    contracts:
      - name: EverclearSpoke
        address: 0x91c40B4135eFea3c5A200388CfE316aa0B172b30
      - name: FeeAdapter
        address: 0xF4a697B7A48e9c7C1944a68a11d3b8D5E716d169

  - id: 8453
    start_block: 0
    confirmed_block_threshold: 10
    contracts:
      - name: EverclearSpoke
        address: 0x91c40B4135eFea3c5A200388CfE316aa0B172b30
      - name: FeeAdapter
        address: 0x4F35c530D3C023717E2BBafdfEacEeE79C4c1e89

rollback_on_reorg: true
